version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laraapps
    restart: always
    volumes:
      - ./app:/var/www
    ports:
      - 8000:80
    networks:
      - laravel-network
    environment:
      - APP_URL=http://localhost:8000
      - DB_HOST=172.16.105.138
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=0r4r3t1Mbuh
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=laravel-bucket
      - AWS_ENDPOINT=http://172.16.105.139:9000

networks:
  laravel-network:
    driver: bridge
