version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    networks:
      - laravel-network
    command: minio server /data

networks:
  laravel-network:
    driver: bridge

volumes:
  minio_data:
