version: '3.8'

services:
  db:
    image: mysql:9.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: 0r4r3t1Mbuh
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
